# Setup
# 指定网站的标题
title: 牟栩荣的个人博客

# 网站的简要描述
description: A simple, beautiful, and powerful Jekyll theme for blogs

# 站点的子目录，如果你的网站托管在子目录下，需要指定  
baseurl: "" # the subpath of your site, e.g. /blog

# 网站的基本 URL 地址
# url: https://xurongmou.github.io
url: https://www.panversenexus.com

# 指定要使用的 Jekyll 主题，如果不使用主题，则为空
# theme: not-pure-poole

# 头像图片的路径
avatar: /avatar.jpeg

# 文章分页设置，每页显示的文章数量
paginate: 5

# 文章永久链接格式
permalink: pretty

# 首页的封面图片路径
cover_image: /bg.jpeg

# 列出要在站点构建过程中使用的插件
# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: vszhub
  card: summary
logo: logo.png
social:
  name: Xurong Mou
  links:
    - https://twitter.com/evanxmou
    - https://github.com/xurongmou
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Xurong Mou
  url: https://github.com/xurongmou/
  email: chungjim77@gmail.com
